// Academic Presets and Comprehensive Test Suites for Regular Language Difference

export interface PresetExample {
  id: string;
  category: 'Classic Academic' | 'Quantifiers (+, ?, *)' | 'Equivalence & Subsets' | 'Binary Alphabets' | 'Complex';
  title: string;
  description: string;
  r1: string;
  r2: string;
  expectedDifference: boolean;
  expectedWitnessDesc: string;
  conceptNote: string;
}

export const PRESET_EXAMPLES: PresetExample[] = [
  {
    id: 'ex-1',
    category: 'Classic Academic',
    title: 'Example 1: Branch Alternation vs Single Loop',
    description: 'R1 allows both b and c in any order after a; R2 only allows b.',
    r1: 'a(b|c)*',
    r2: 'ab*',
    expectedDifference: true,
    expectedWitnessDesc: 'ac',
    conceptNote: 'String "ac" satisfies a(b|c)* since "c" is valid in R1, but rejected by R2 which only allows "b".',
  },
  {
    id: 'ex-2',
    category: 'Classic Academic',
    title: 'Example 2: Union vs Single Symbol',
    description: 'R1 accepts either "a" or "b"; R2 accepts only "a".',
    r1: 'a|b',
    r2: 'a',
    expectedDifference: true,
    expectedWitnessDesc: 'b',
    conceptNote: 'String "b" is in L(a|b) but not in L(a).',
  },
  {
    id: 'ex-3',
    category: 'Classic Academic',
    title: 'Example 3: Repeated Suffix vs Fixed Length',
    description: 'R1 accepts "a", "ab", "abb"...; R2 accepts only "a".',
    r1: 'ab*',
    r2: 'a',
    expectedDifference: true,
    expectedWitnessDesc: 'ab',
    conceptNote: 'String "ab" is accepted by ab* (1 repetition of b) but rejected by fixed string "a".',
  },
  {
    id: 'ex-4',
    category: 'Equivalence & Subsets',
    title: 'Example 4: Syntactically Different Equivalent Languages',
    description: 'Both expressions generate the exact same language: zero or more "a"s.',
    r1: 'a*',
    r2: '(a)*',
    expectedDifference: false,
    expectedWitnessDesc: 'None (L(R1) ⊆ L(R2))',
    conceptNote: 'Parentheses around a single literal do not alter the regular language. L(R1) = L(R2), so difference is empty.',
  },
  {
    id: 'ex-5',
    category: 'Equivalence & Subsets',
    title: 'Example 5: Subset Language (Empty Difference)',
    description: 'L(R1) is a strict subset of L(R2).',
    r1: 'a',
    r2: 'a|b',
    expectedDifference: false,
    expectedWitnessDesc: 'None (L(R1) ⊆ L(R2))',
    conceptNote: 'Every string generated by "a" is trivially contained in "a|b". Thus L(R1) − L(R2) = ∅.',
  },
  {
    id: 'ex-6',
    category: 'Quantifiers (+, ?, *)',
    title: 'Example 6: One-or-More (+) vs Zero-or-More (*)',
    description: 'R1 requires at least one repeat; R2 allows zero repeats.',
    r1: 'a+',
    r2: 'a*',
    expectedDifference: false,
    expectedWitnessDesc: 'None (L(a+) ⊂ L(a*))',
    conceptNote: 'Since L(a+) ⊂ L(a*), every string in a+ is already inside a*.',
  },
  {
    id: 'ex-7',
    category: 'Quantifiers (+, ?, *)',
    title: 'Example 7: Optional (?) with Epsilon Witness',
    description: 'R1 allows the empty string via optional quantifier; R2 requires exact match.',
    r1: 'a?',
    r2: 'a',
    expectedDifference: true,
    expectedWitnessDesc: 'ε (empty string)',
    conceptNote: 'The empty string ε is in L(a?) but rejected by L(a).',
  },
  {
    id: 'ex-8',
    category: 'Quantifiers (+, ?, *)',
    title: 'Example 8: Plus Quantifier Position Asymmetry',
    description: 'R1 repeats "a" before "b"; R2 repeats "b" after "a".',
    r1: 'a+b',
    r2: 'ab+',
    expectedDifference: true,
    expectedWitnessDesc: 'aab',
    conceptNote: 'String "aab" has two "a"s and one "b". Accepted by a+b, rejected by ab+.',
  },
  {
    id: 'ex-9',
    category: 'Binary Alphabets',
    title: 'Example 9: Binary Ending Pattern (ab vs ba)',
    description: 'R1 accepts any binary string ending in "00"; R2 accepts strings ending in "11".',
    r1: '(0|1)*00',
    r2: '(0|1)*11',
    expectedDifference: true,
    expectedWitnessDesc: '00',
    conceptNote: 'String "00" ends in "00" and not "11".',
  },
  {
    id: 'ex-10',
    category: 'Complex',
    title: 'Example 10: Nested Groups and Disjoint Languages',
    description: 'R1 generates words over {a,b}; R2 generates words over {c,d}.',
    r1: '(a|b)+',
    r2: '(c|d)+',
    expectedDifference: true,
    expectedWitnessDesc: 'a',
    conceptNote: 'Alphabets are disjoint. "a" is accepted by R1 and rejected by R2.',
  },
];

export interface InvalidTestCase {
  id: string;
  name: string;
  r1: string;
  r2: string;
  expectedErrorSnippet: string;
  explanation: string;
}

export const INVALID_TEST_CASES: InvalidTestCase[] = [
  {
    id: 'inv-1',
    name: 'Unmatched Parenthesis',
    r1: '(a|b',
    r2: 'a',
    expectedErrorSnippet: 'Unmatched opening parenthesis',
    explanation: 'The opening "(" is never closed before the end of the expression.',
  },
  {
    id: 'inv-2',
    name: 'Duplicate Quantifiers (a**)',
    r1: 'a**',
    r2: 'b',
    expectedErrorSnippet: 'Consecutive quantifier operators',
    explanation: 'Applying multiple postfix quantifiers without grouping is ambiguous and invalid in standard regular language syntax.',
  },
  {
    id: 'inv-3',
    name: 'Leading Postfix Operator (*a)',
    r1: '*a',
    r2: 'b',
    expectedErrorSnippet: 'cannot appear at the start',
    explanation: 'A Kleene star requires an operand preceding it.',
  },
  {
    id: 'inv-4',
    name: 'Trailing Alternation (a|)',
    r1: 'a|',
    r2: 'b',
    expectedErrorSnippet: 'requires an expression on its right',
    explanation: 'The union operator "|" must have both left and right subexpressions.',
  },
  {
    id: 'inv-5',
    name: 'Empty Parentheses ()',
    r1: '()',
    r2: 'a',
    expectedErrorSnippet: 'Empty parentheses',
    explanation: 'Empty group with no content is prohibited; use explicit "ε" for the empty string.',
  },
  {
    id: 'inv-6',
    name: 'Empty Input',
    r1: '',
    r2: 'a',
    expectedErrorSnippet: 'cannot be empty',
    explanation: 'A valid regular expression string is required.',
  },
];
